# Generated by Django 5.2.4 on 2025-09-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abfahrt',
            name='anhaenger',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
