# Generated by Django 5.2.4 on 2025-09-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_abfahrt_anhaenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zollamt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('typ', models.CharField(choices=[('abgang', 'Abgangszollstelle'), ('grenz', 'Grenzzollstelle')], max_length=10)),
            ],
        ),
    ]
