# Generated by Django 5.1.6 on 2025-10-20 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_zollamt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abfahrt',
            options={'verbose_name': 'Abfahrt', 'verbose_name_plural': 'Abfahrten'},
        ),
        migrations.AlterModelOptions(
            name='zollamt',
            options={'verbose_name': 'Zollamt', 'verbose_name_plural': 'Zollämter'},
        ),
        migrations.AddField(
            model_name='abfahrt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zollamt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
