# Generated by Django 6.0.4 on 2026-07-19 16:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_abfahrt_options_alter_zollamt_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_clearance', models.CharField(blank=True, max_length=100, null=True)),
                ('eur1_certificate', models.CharField(blank=True, max_length=100, null=True)),
                ('import_clearance', models.CharField(blank=True, max_length=100, null=True)),
                ('transit_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zollabfertigung',
                'verbose_name_plural': 'Zollabfertigungen',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Nur 11 Ziffern erlaubt.')])),
                ('sender', models.CharField(blank=True, max_length=200, null=True)),
                ('destination_country', models.CharField(blank=True, max_length=2, null=True)),
                ('abfahrt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.abfahrt')),
                ('customs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sendung',
                'verbose_name_plural': 'Sendungen',
            },
        ),
        migrations.CreateModel(
            name='Colli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collis', to='main.shipment')),
            ],
            options={
                'verbose_name': 'Colli',
                'verbose_name_plural': 'Collis',
            },
        ),
        migrations.CreateModel(
            name='TransitDocument',
            fields=[
                ('t_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('t_colli_quantity', models.IntegerField()),
                ('t_weight', models.FloatField(blank=True, null=True)),
                ('t_customs_office', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transitdokument',
                'verbose_name_plural': 'Transitdokumente',
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='transit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.transitdocument'),
        ),
    ]
