# Generated by Django 6.0.4 on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customs_shipment_colli_transitdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitdocument',
            name='t_colli_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transitdocument',
            name='t_goods_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
